/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fajar Ramadhan
 */
public class Kalkulator extends javax.swing.JFrame {
    
    String angka = "";
    double jumlah, bil1, bil2;
    int pilih;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Kalkulator.class.getName());

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        TombolDelapan = new javax.swing.JButton();
        TombolTujuh = new javax.swing.JButton();
        TombolSembilan = new javax.swing.JButton();
        TombolEmpat = new javax.swing.JButton();
        TombolSatu = new javax.swing.JButton();
        TombolTitik = new javax.swing.JButton();
        TombolLima = new javax.swing.JButton();
        TombolDua = new javax.swing.JButton();
        TombolEnol = new javax.swing.JButton();
        TombolEnam = new javax.swing.JButton();
        TombolTiga = new javax.swing.JButton();
        TombolUlangi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        TombolTambah = new javax.swing.JButton();
        TombolKali = new javax.swing.JButton();
        TombolSamaDengan = new javax.swing.JButton();
        TombolBackspace = new javax.swing.JButton();
        TombolKurang = new javax.swing.JButton();
        TombolBagi = new javax.swing.JButton();
        TombolPersen = new javax.swing.JButton();
        TombolExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setToolTipText("");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        TombolDelapan.setBackground(new java.awt.Color(153, 204, 255));
        TombolDelapan.setForeground(new java.awt.Color(0, 0, 0));
        TombolDelapan.setText("8");
        TombolDelapan.addActionListener(this::TombolDelapanActionPerformed);

        TombolTujuh.setBackground(new java.awt.Color(153, 204, 255));
        TombolTujuh.setForeground(new java.awt.Color(0, 0, 0));
        TombolTujuh.setText("7");
        TombolTujuh.addActionListener(this::TombolTujuhActionPerformed);

        TombolSembilan.setBackground(new java.awt.Color(153, 204, 255));
        TombolSembilan.setForeground(new java.awt.Color(0, 0, 0));
        TombolSembilan.setText("9");
        TombolSembilan.addActionListener(this::TombolSembilanActionPerformed);

        TombolEmpat.setBackground(new java.awt.Color(153, 204, 255));
        TombolEmpat.setForeground(new java.awt.Color(0, 0, 0));
        TombolEmpat.setText("4");
        TombolEmpat.addActionListener(this::TombolEmpatActionPerformed);

        TombolSatu.setBackground(new java.awt.Color(153, 204, 255));
        TombolSatu.setForeground(new java.awt.Color(0, 0, 0));
        TombolSatu.setText("1");
        TombolSatu.addActionListener(this::TombolSatuActionPerformed);

        TombolTitik.setBackground(new java.awt.Color(153, 204, 255));
        TombolTitik.setForeground(new java.awt.Color(0, 0, 0));
        TombolTitik.setText(".");
        TombolTitik.addActionListener(this::TombolTitikActionPerformed);

        TombolLima.setBackground(new java.awt.Color(153, 204, 255));
        TombolLima.setForeground(new java.awt.Color(0, 0, 0));
        TombolLima.setText("5");
        TombolLima.addActionListener(this::TombolLimaActionPerformed);

        TombolDua.setBackground(new java.awt.Color(153, 204, 255));
        TombolDua.setForeground(new java.awt.Color(0, 0, 0));
        TombolDua.setText("2");
        TombolDua.addActionListener(this::TombolDuaActionPerformed);

        TombolEnol.setBackground(new java.awt.Color(153, 204, 255));
        TombolEnol.setForeground(new java.awt.Color(0, 0, 0));
        TombolEnol.setText("0");
        TombolEnol.addActionListener(this::TombolEnolActionPerformed);

        TombolEnam.setBackground(new java.awt.Color(153, 204, 255));
        TombolEnam.setForeground(new java.awt.Color(0, 0, 0));
        TombolEnam.setText("6");
        TombolEnam.addActionListener(this::TombolEnamActionPerformed);

        TombolTiga.setBackground(new java.awt.Color(153, 204, 255));
        TombolTiga.setForeground(new java.awt.Color(0, 0, 0));
        TombolTiga.setText("3");
        TombolTiga.addActionListener(this::TombolTigaActionPerformed);

        TombolUlangi.setBackground(new java.awt.Color(153, 204, 255));
        TombolUlangi.setForeground(new java.awt.Color(0, 0, 0));
        TombolUlangi.setText("C");
        TombolUlangi.setToolTipText("");
        TombolUlangi.addActionListener(this::TombolUlangiActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TombolDelapan, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TombolEmpat, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TombolSatu, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TombolTitik, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TombolEnol, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TombolUlangi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(TombolDua, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TombolTiga, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TombolTujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TombolLima, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TombolSembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TombolEnam, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolDelapan)
                    .addComponent(TombolTujuh)
                    .addComponent(TombolSembilan))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolEmpat)
                    .addComponent(TombolLima)
                    .addComponent(TombolEnam))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolTiga)
                    .addComponent(TombolDua)
                    .addComponent(TombolSatu))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolUlangi)
                    .addComponent(TombolEnol)
                    .addComponent(TombolTitik))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        TombolTambah.setBackground(new java.awt.Color(153, 204, 255));
        TombolTambah.setForeground(new java.awt.Color(0, 0, 0));
        TombolTambah.setText("+");
        TombolTambah.addActionListener(this::TombolTambahActionPerformed);

        TombolKali.setBackground(new java.awt.Color(153, 204, 255));
        TombolKali.setForeground(new java.awt.Color(0, 0, 0));
        TombolKali.setText("*");
        TombolKali.addActionListener(this::TombolKaliActionPerformed);

        TombolSamaDengan.setBackground(new java.awt.Color(153, 204, 255));
        TombolSamaDengan.setForeground(new java.awt.Color(0, 0, 0));
        TombolSamaDengan.setText("=");
        TombolSamaDengan.addActionListener(this::TombolSamaDenganActionPerformed);

        TombolBackspace.setBackground(new java.awt.Color(153, 204, 255));
        TombolBackspace.setForeground(new java.awt.Color(0, 0, 0));
        TombolBackspace.setText("B");
        TombolBackspace.addActionListener(this::TombolBackspaceActionPerformed);

        TombolKurang.setBackground(new java.awt.Color(153, 204, 255));
        TombolKurang.setForeground(new java.awt.Color(0, 0, 0));
        TombolKurang.setText("-");
        TombolKurang.addActionListener(this::TombolKurangActionPerformed);

        TombolBagi.setBackground(new java.awt.Color(153, 204, 255));
        TombolBagi.setForeground(new java.awt.Color(0, 0, 0));
        TombolBagi.setText("/");
        TombolBagi.addActionListener(this::TombolBagiActionPerformed);

        TombolPersen.setBackground(new java.awt.Color(153, 204, 255));
        TombolPersen.setForeground(new java.awt.Color(0, 0, 0));
        TombolPersen.setText("%");
        TombolPersen.addActionListener(this::TombolPersenActionPerformed);

        TombolExit.setBackground(new java.awt.Color(153, 204, 255));
        TombolExit.setForeground(new java.awt.Color(0, 0, 0));
        TombolExit.setText("E");
        TombolExit.addActionListener(this::TombolExitActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(TombolBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(TombolExit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(TombolSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TombolPersen, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(TombolKali, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TombolBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(TombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TombolKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolTambah)
                    .addComponent(TombolKurang))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolKali)
                    .addComponent(TombolBagi))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolSamaDengan)
                    .addComponent(TombolPersen))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolBackspace)
                    .addComponent(TombolExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolEnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolEnamActionPerformed
        angka += "6";
        jTextField1.setText(angka);
    }//GEN-LAST:event_TombolEnamActionPerformed

    private void TombolUlangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolUlangiActionPerformed
        jTextField1.setText("");
        bil1 = 0;
        bil2 = 0;
        jumlah = 0;
        angka = "";
    }//GEN-LAST:event_TombolUlangiActionPerformed

    private void TombolTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolTambahActionPerformed
        bil1 = Double.parseDouble(angka);
        jTextField1.setText("+");
        angka = "";
        pilih = 1;
    }//GEN-LAST:event_TombolTambahActionPerformed

    private void TombolKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolKaliActionPerformed
        bil1 = Double.parseDouble(angka);
        jTextField1.setText("*");
        angka = "";
        pilih = 3;
    }//GEN-LAST:event_TombolKaliActionPerformed

    private void TombolSamaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolSamaDenganActionPerformed
        switch (pilih) {
        case 1:
            bil2 = Double.parseDouble(angka);
            jumlah = bil1 + bil2;
            angka = Double.toString(jumlah);
            jTextField1.setText(angka);
            break;
        case 2:
            bil2 = Double.parseDouble(angka);
            jumlah = bil1 - bil2;
            angka = Double.toString(jumlah);
            jTextField1.setText(angka);
            break;
        case 3:
            bil2 = Double.parseDouble(angka);
            jumlah = bil1 * bil2;
            angka = Double.toString(jumlah);
            jTextField1.setText(angka);
            break;
        case 4:
            bil2 = Double.parseDouble(angka);
            if (bil2 == 0) {
                jTextField1.setText("Error");
                angka = "";
            } else {
                jumlah = bil1 / bil2;
                angka = Double.toString(jumlah);
                jTextField1.setText(angka);
            }
            break;
        case 5:
            bil2 = Double.parseDouble(angka);
            jumlah = bil1 % bil2;
            angka = Double.toString(jumlah);
            jTextField1.setText(angka);
            break;
        }
    }//GEN-LAST:event_TombolSamaDenganActionPerformed

    private void TombolBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolBackspaceActionPerformed
        if (angka.length() > 0) {
        angka = angka.substring(0, angka.length() - 1);
        jTextField1.setText(angka);
        }
    }//GEN-LAST:event_TombolBackspaceActionPerformed

    private void TombolKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolKurangActionPerformed
        bil1 = Double.parseDouble(angka);
        jTextField1.setText("-");
        angka = "";
        pilih = 2;
    }//GEN-LAST:event_TombolKurangActionPerformed

    private void TombolBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolBagiActionPerformed
        bil1 = Double.parseDouble(angka);
        jTextField1.setText("/");
        angka = "";
        pilih = 4;
    }//GEN-LAST:event_TombolBagiActionPerformed

    private void TombolPersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolPersenActionPerformed
        bil1 = Double.parseDouble(angka);
        jTextField1.setText("%");
        angka = "";
        pilih = 5;
    }//GEN-LAST:event_TombolPersenActionPerformed

    private void TombolExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_TombolExitActionPerformed

    private void TombolEmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolEmpatActionPerformed
        angka += "4";
        jTextField1.setText(angka);
    }//GEN-LAST:event_TombolEmpatActionPerformed

    private void TombolSembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolSembilanActionPerformed
        angka += "9";
        jTextField1.setText(angka);
    }//GEN-LAST:event_TombolSembilanActionPerformed

    private void TombolEnolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolEnolActionPerformed
        angka += "0";
        jTextField1.setText(angka);
    }//GEN-LAST:event_TombolEnolActionPerformed

    private void TombolDelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolDelapanActionPerformed
        angka += "8";
        jTextField1.setText(angka);
    }//GEN-LAST:event_TombolDelapanActionPerformed

    private void TombolTujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolTujuhActionPerformed
        angka += "7";
        jTextField1.setText(angka);
    }//GEN-LAST:event_TombolTujuhActionPerformed

    private void TombolLimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolLimaActionPerformed
        angka += "5";
        jTextField1.setText(angka);
    }//GEN-LAST:event_TombolLimaActionPerformed

    private void TombolSatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolSatuActionPerformed
        angka += "1";
        jTextField1.setText(angka);
    }//GEN-LAST:event_TombolSatuActionPerformed

    private void TombolDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolDuaActionPerformed
        angka += "2";
        jTextField1.setText(angka);
    }//GEN-LAST:event_TombolDuaActionPerformed

    private void TombolTigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolTigaActionPerformed
        angka += "3";
        jTextField1.setText(angka);
    }//GEN-LAST:event_TombolTigaActionPerformed

    private void TombolTitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolTitikActionPerformed
        angka += ".";
        jTextField1.setText(angka);
    }//GEN-LAST:event_TombolTitikActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Kalkulator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TombolBackspace;
    private javax.swing.JButton TombolBagi;
    private javax.swing.JButton TombolDelapan;
    private javax.swing.JButton TombolDua;
    private javax.swing.JButton TombolEmpat;
    private javax.swing.JButton TombolEnam;
    private javax.swing.JButton TombolEnol;
    private javax.swing.JButton TombolExit;
    private javax.swing.JButton TombolKali;
    private javax.swing.JButton TombolKurang;
    private javax.swing.JButton TombolLima;
    private javax.swing.JButton TombolPersen;
    private javax.swing.JButton TombolSamaDengan;
    private javax.swing.JButton TombolSatu;
    private javax.swing.JButton TombolSembilan;
    private javax.swing.JButton TombolTambah;
    private javax.swing.JButton TombolTiga;
    private javax.swing.JButton TombolTitik;
    private javax.swing.JButton TombolTujuh;
    private javax.swing.JButton TombolUlangi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
